version: '3.8'

services:
  octc:
    platform: linux/amd64
    image: ghcr.io/indicardo/ocn:latest
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mongodb
      - redis
      - rabbitmq
      - couchdb
    ports:
      - "3000:3000"
    volumes:
      - ../OCN-Data:/minecraft/repo/data
    environment:
      RAILS_ENV: production
      WEB_ROLE: octc

  api:
    platform: linux/amd64
    image: ghcr.io/indicardo/ocn:latest
    depends_on:
      - mongodb
      - redis
      - rabbitmq
      - couchdb
    ports:
      - "3010:3000"
    volumes:
      - ../OCN-Data:/minecraft/repo/data
    environment:
      RAILS_ENV: production
      WEB_ROLE: api

  worker:
    platform: linux/amd64
    image: ghcr.io/indicardo/ocn:latest
    depends_on:
      - mongodb
      - redis
      - rabbitmq
      - couchdb
    volumes:
      - ../OCN-Data:/minecraft/repo/data
    command: config/worker.rb

  mongodb:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ../mongodb_data:/data/db

  redis:
    image: redis

  rabbitmq:
    image: rabbitmq
    restart: always
    ports:
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: overcast
      RABBITMQ_DEFAULT_PASS: overcast

  couchdb:
    image: couchdb:2.3.1
    restart: always
    ports:
      - "5984:5984"
    volumes:
      - ../couchdb_data:/opt/couchdb/data