production:
  clients:
    default:
      database: pgm-prod
      hosts:
        - mongodb:27017
  options:
    raise_not_found_error: false

staging:
  clients:
    default:
      database: pgm-prod
      hosts:
        - mongodb:27017
  options:
    raise_not_found_error: false

development:
  clients:
    default:
      database: pgm-prod
      hosts:
        - localhost:27017
  options:
    raise_not_found_error: false